apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: person-notifier
spec:
  schedule: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jobs
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/peoplefinder/peoplefinder-ecr:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-rds-output
                    key: url
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-rds-output
                    key: database_password
              - name: S3_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-s3-output
                    key: bucket_name
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-s3-output
                    key: access_key_id
              - name: S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-s3-output
                    key: secret_access_key
            envFrom:
            - configMapRef:
                name: environment-variables
            - secretRef:
                name: app-secrets
            command:
              - /bin/sh
              - "-c"
              - "rails runner 'NotificationSender.new.send!'"
          restartPolicy: OnFailure
