apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: profile-completions-report-publish
spec:
  schedule: "40 6 * * 1-5"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: peoplefinder
          containers:
          - name: jobs
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/peoplefinder/peoplefinder-ecr:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-rds-output
                    key: url
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-rds-output
                    key: database_password
              - name: S3_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-s3-output
                    key: bucket_name
              - name: MOJ_PF_ES_URL
                valueFrom:
                  secretKeyRef:
                    name: peoplefinder-opensearch-output
                    key: proxy_url
            envFrom:
            - configMapRef:
                name: environment-variables
            - secretRef:
                name: app-secrets
            command:
              - /bin/sh
              - "-c"
              - "rails runner 'GeckoboardPublisher::ProfileCompletionsReport.new.publish!(force: true)'"
          restartPolicy: OnFailure
