AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'config/initializers/simple_form.rb'
    - 'config/unicorn.rb'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/brakeman.rake'
    - 'lib/tasks/elasticsearch.rake'
    - 'spec/dummy/db/**/*'
    - 'smoke_test'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

# Just indent parameters by two spaces. It's less volatile if methods change,
# and there's less busy work lining things up.
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/CollectionMethods:
  PreferredMethods:
    inject: 'inject'
    reduce: 'inject'

# Chain methods with trailing dots.
Style/DotPosition:
  EnforcedStyle: trailing

# Percent-formatting and hash interpolation both have their place. Don't
# enforce any particular one.
Style/FormatString:
  Enabled: false

# It's not really clearer to replace every if with a return if.
Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Don't worry about long methods in specs.
Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'spec/**/*'

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

# Prefer sensible naming to comments everywhere.
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# Would enforce do_y if x over if x / do y / end. As with GuardClause above,
# this enforces code organisation that doesn't necesarily make things clearer.
Style/IfUnlessModifier:
  Enabled: false

Style/CaseEquality:
  Enabled: false

# Allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/ClassAndModuleChildren:
  Enabled: false

require: rubocop-rspec

Style/RegexpLiteral:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/AlignHash:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 115

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/profile.rb'

Rails/TimeZone:
  Exclude:
    - 'spec/**/*'

Rails/Date:
  Exclude:
    - 'spec/**/*'

Lint/Debugger:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'spec/**/*'

Style/IndentArray:
  Exclude:
    - 'spec/**/*'

Style/SpaceAroundOperators:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/*'

Style/ZeroLengthPredicate:
  Exclude:
    - 'Gemfile'

RSpec/NotToNot:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
