services:
  pg:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - pg
    ports:
      - "3000:3000"
    command: bundle exec rails s -b '0.0.0.0' # Ensure it binds to all interfaces
    environment:
      DOCKER_STATE: migrate
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:@pg:5432/postgres
      SECRET_KEY_BASE: development_key_here

  worker:
    build: .
    depends_on:
      - pg
    command: bundle exec sidekiq # or whatever your worker command is
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:@pg:5432/postgres