require 'rails_helper'

RSpec.describe MultiUserCSVRenderer do
  it 'combines CSVs generated by the individual renderer' do
    user_a = build(:user)
    user_b = build(:user)
    renderer_a = double(UserCSVRenderer, to_csv: "AAA\n")
    renderer_b = double(UserCSVRenderer, to_csv: "BBB\n")
    allow(UserCSVRenderer).to receive(:new).with(user_a).and_return(renderer_a)
    allow(UserCSVRenderer).to receive(:new).with(user_b).and_return(renderer_b)

    expect(described_class.new([user_a, user_b]).to_csv).to eql("AAA\n\nBBB\n")
  end
end
