apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peoplefinder-ingress
  namespace: peoplefinder-demo
spec:
  tls:
    - hosts: demo.peoplefinder.service.gov.uk
      secretName: peoplefinder-certificate
  rules:
    - host: demo.peoplefinder.service.gov.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: peoplefinder-service
              servicePort: 3000
