require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MinistersController do

  # This should return the minimal set of attributes required to create a valid
  # Minister. As you add validations to Minister, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MinistersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ministers as @ministers" do
      minister = Minister.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ministers).should eq([minister])
    end
  end

  describe "GET show" do
    it "assigns the requested minister as @minister" do
      minister = Minister.create! valid_attributes
      get :show, {:id => minister.to_param}, valid_session
      assigns(:minister).should eq(minister)
    end
  end

  describe "GET new" do
    it "assigns a new minister as @minister" do
      get :new, {}, valid_session
      assigns(:minister).should be_a_new(Minister)
    end
  end

  describe "GET edit" do
    it "assigns the requested minister as @minister" do
      minister = Minister.create! valid_attributes
      get :edit, {:id => minister.to_param}, valid_session
      assigns(:minister).should eq(minister)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Minister" do
        expect {
          post :create, {:minister => valid_attributes}, valid_session
        }.to change(Minister, :count).by(1)
      end

      it "assigns a newly created minister as @minister" do
        post :create, {:minister => valid_attributes}, valid_session
        assigns(:minister).should be_a(Minister)
        assigns(:minister).should be_persisted
      end

      it "redirects to the created minister" do
        post :create, {:minister => valid_attributes}, valid_session
        response.should redirect_to(Minister.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved minister as @minister" do
        # Trigger the behavior that occurs when invalid params are submitted
        Minister.any_instance.stub(:save).and_return(false)
        post :create, {:minister => { "name" => "invalid value" }}, valid_session
        assigns(:minister).should be_a_new(Minister)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Minister.any_instance.stub(:save).and_return(false)
        post :create, {:minister => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested minister" do
        minister = Minister.create! valid_attributes
        # Assuming there are no other ministers in the database, this
        # specifies that the Minister created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Minister.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => minister.to_param, :minister => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested minister as @minister" do
        minister = Minister.create! valid_attributes
        put :update, {:id => minister.to_param, :minister => valid_attributes}, valid_session
        assigns(:minister).should eq(minister)
      end

      it "redirects to the minister" do
        minister = Minister.create! valid_attributes
        put :update, {:id => minister.to_param, :minister => valid_attributes}, valid_session
        response.should redirect_to(minister)
      end
    end

    describe "with invalid params" do
      it "assigns the minister as @minister" do
        minister = Minister.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Minister.any_instance.stub(:save).and_return(false)
        put :update, {:id => minister.to_param, :minister => { "name" => "invalid value" }}, valid_session
        assigns(:minister).should eq(minister)
      end

      it "re-renders the 'edit' template" do
        minister = Minister.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Minister.any_instance.stub(:save).and_return(false)
        put :update, {:id => minister.to_param, :minister => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested minister" do
      minister = Minister.create! valid_attributes
      expect {
        delete :destroy, {:id => minister.to_param}, valid_session
      }.to change(Minister, :count).by(-1)
    end

    it "redirects to the ministers list" do
      minister = Minister.create! valid_attributes
      delete :destroy, {:id => minister.to_param}, valid_session
      response.should redirect_to(ministers_url)
    end
  end

end
