require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgressesController do

  # This should return the minimal set of attributes required to create a valid
  # Progress. As you add validations to Progress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "progress_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all progresses as @progresses" do
      progress = Progress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:progresses).should eq([progress])
    end
  end

  describe "GET show" do
    it "assigns the requested progress as @progress" do
      progress = Progress.create! valid_attributes
      get :show, {:id => progress.to_param}, valid_session
      assigns(:progress).should eq(progress)
    end
  end

  describe "GET new" do
    it "assigns a new progress as @progress" do
      get :new, {}, valid_session
      assigns(:progress).should be_a_new(Progress)
    end
  end

  describe "GET edit" do
    it "assigns the requested progress as @progress" do
      progress = Progress.create! valid_attributes
      get :edit, {:id => progress.to_param}, valid_session
      assigns(:progress).should eq(progress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Progress" do
        expect {
          post :create, {:progress => valid_attributes}, valid_session
        }.to change(Progress, :count).by(1)
      end

      it "assigns a newly created progress as @progress" do
        post :create, {:progress => valid_attributes}, valid_session
        assigns(:progress).should be_a(Progress)
        assigns(:progress).should be_persisted
      end

      it "redirects to the created progress" do
        post :create, {:progress => valid_attributes}, valid_session
        response.should redirect_to(Progress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved progress as @progress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Progress.any_instance.stub(:save).and_return(false)
        post :create, {:progress => { "progress_id" => "invalid value" }}, valid_session
        assigns(:progress).should be_a_new(Progress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Progress.any_instance.stub(:save).and_return(false)
        post :create, {:progress => { "progress_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested progress" do
        progress = Progress.create! valid_attributes
        # Assuming there are no other progresses in the database, this
        # specifies that the Progress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Progress.any_instance.should_receive(:update).with({ "progress_id" => "1" })
        put :update, {:id => progress.to_param, :progress => { "progress_id" => "1" }}, valid_session
      end

      it "assigns the requested progress as @progress" do
        progress = Progress.create! valid_attributes
        put :update, {:id => progress.to_param, :progress => valid_attributes}, valid_session
        assigns(:progress).should eq(progress)
      end

      it "redirects to the progress" do
        progress = Progress.create! valid_attributes
        put :update, {:id => progress.to_param, :progress => valid_attributes}, valid_session
        response.should redirect_to(progress)
      end
    end

    describe "with invalid params" do
      it "assigns the progress as @progress" do
        progress = Progress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Progress.any_instance.stub(:save).and_return(false)
        put :update, {:id => progress.to_param, :progress => { "progress_id" => "invalid value" }}, valid_session
        assigns(:progress).should eq(progress)
      end

      it "re-renders the 'edit' template" do
        progress = Progress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Progress.any_instance.stub(:save).and_return(false)
        put :update, {:id => progress.to_param, :progress => { "progress_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested progress" do
      progress = Progress.create! valid_attributes
      expect {
        delete :destroy, {:id => progress.to_param}, valid_session
      }.to change(Progress, :count).by(-1)
    end

    it "redirects to the progresses list" do
      progress = Progress.create! valid_attributes
      delete :destroy, {:id => progress.to_param}, valid_session
      response.should redirect_to(progresses_url)
    end
  end

end
