apiVersion: apps/v1
kind: Deployment
metadata:
  name: peoplefinder
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: peoplefinder
  template:
    metadata:
      labels:
        app: peoplefinder
    spec:
      containers:
        - name: webapp
          imagePullPolicy: Always
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/peoplefinder/peoplefinder-ecr:latest
          ports:
            - containerPort: 3000
          command: ["./run.sh"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-rds-output
                  key: url
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-rds-output
                  key: database_password
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: bucket_name
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: access_key_id
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: secret_access_key
          envFrom:
            - configMapRef:
                name: environment-variables
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
                - name: X-Forwarded-Ssl
                  value: "on"
              initialDelaySeconds: 40
              periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
                - name: X-Forwarded-Ssl
                  value: "on"
            initialDelaySeconds: 40
            periodSeconds: 60
        - name: jobs
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/peoplefinder/peoplefinder-ecr:latest
          ports:
            - containerPort: 3000
          command: ["./run.sh"]
          args: ["worker"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-rds-output
                  key: url
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-rds-output
                  key: database_password
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: bucket_name
            - name: S3_KEY
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: access_key_id
            - name: S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: peoplefinder-s3-output
                  key: secret_access_key
          envFrom:
            - configMapRef:
                name: environment-variables
            - secretRef:
                name: app-secrets
